name: Jira PR Automation

on:
  repository_dispatch:
    types: [jira_transition] # This is the correct configuration

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Jira Issue Details
        id: jira_info
        uses: actions/github-script@v6
        with:
          script: |
            const payload = context.payload.inputs.client_payload; // Access client_payload correctly
            const issueKey = payload.issue.key;
            const issueSummary = payload.issue.fields.summary;
            const changelog = payload.changelog;

            if (changelog && changelog.items.some(item => item.field == 'status' && item.to == 'REQUEST FOR RELEASE')) {
              const branchName = `feature/${issueKey}-${issueSummary.replace(/\s+/g, '-').toLowerCase()}`;
              core.setOutput('issueKey', issueKey);
              core.setOutput('branchName', branchName);
              core.setOutput('issueSummary', issueSummary);
            } else {
              core.setFailed('Issue not transitioned to REQUEST FOR RELEASE. Exiting.');
            }

      - name: Create/Checkout Feature Branch
        if: steps.jira_info.outcome == 'success'
        run: |
          git checkout -b ${{ steps.jira_info.outputs.branchName }} || git checkout ${{ steps.jira_info.outputs.branchName }}

      - name: Make Changes (Your Code Changes Here)
        if: steps.jira_info.outcome == 'success'
        run: |
          # ... (Your code change commands) ...
          git add .
          git commit -m "Automated commit for ${issueKey}: ${issueSummary}"

      - name: Push Changes
        if: steps.jira_info.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.jira_info.outputs.branchName }}

      - name: Create Pull Request
        if: steps.jira_info.outcome == 'success'
        uses: peter-murray/github-automatic-pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ steps.jira_info.outputs.branchName }}
          title: "PR: ${{ steps.jira_info.outputs.issueKey }} - ${{ steps.jira_info.outputs.branchName }}"
          body: |
            Automated PR created for Jira ticket ${{ steps.jira_info.outputs.issueKey }}.
            Ticket Summary: ${{ steps.jira_info.outputs.issueSummary }}
            [Link to Jira Ticket](YOUR_JIRA_URL/browse/${{ steps.jira_info.outputs.issueKey }})
          automatic_merge: false